<?php


namespace frontend\controllers;


class TasksController extends TableController
{

    public function actionCreate()
    {
        return parent::actionCreate(); // TODO: Change the autogenerated stub
    }

}
