<?php

namespace frontend\validators;

use yii\validators\Validator;

class RemoteEmailValidator extends Validator
{
    protected function validateValue($value)
    {
        parent::validateValue($value); // TODO: Change the autogenerated stub
    }

}
